spring.application.name=backend


application.security.jwt.secret-key=VGhpc0lzQVNlY3JldEtleUZvckpXVEJvZHlQaWxvdDEyMw==
application.security.jwt.expiration=2592000000

spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
spring.datasource.username=postgres.siazymkepzvidbhyljqy
spring.datasource.password=Dangvu01072004@

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Gemini Config
gemini.api.key=${GEMINI_API_KEY:YOUR_GEMINI_API_KEY}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/
gemini.model=gemini-2.5-flash

# Google Auth Client ID (Web Client ID from google-services.json)
google.client.id=517107633218-u5u15mb0iuc8j6po8s6mblrc37c6vvd2.apps.googleusercontent.com

# Firebase Configuration
firebase.config-path=file:secrets/firebase-service-account.json