spring.application.name=backend


application.security.jwt.secret-key=VGhpc0lzQVNlY3JldEtleUZvckpXVEJvZHlQaWxvdDEyMw==
application.security.jwt.expiration=86400000

spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
spring.datasource.username=postgres.siazymkepzvidbhyljqy
spring.datasource.password=Dangvu01072004@

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update